DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS mypages CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS teampages CASCADE;
DROP TABLE IF EXISTS matchboards CASCADE;
DROP TABLE IF EXISTS memberboards CASCADE;
DROP TABLE IF EXISTS memberforms CASCADE;
DROP TABLE IF EXISTS matchforms CASCADE;
DROP TABLE IF EXISTS users_teams CASCADE;

CREATE TABLE IF NOT EXISTS users (
  user_id SERIAL NOT NULL,
  username VARCHAR(30) NOT NULL,
  password VARCHAR(255) NOT NULL,
  authority VARCHAR(10) NOT NULL,
  tel VARCHAR(15) NOT NULL,
  name VARCHAR(10) NOT NULL,
  age VARCHAR(2) NOT NULL,
  birth_date VARCHAR(15) NOT NULL,
  prefecture VARCHAR(5) NOT NULL,
  city VARCHAR(10) NOT NULL,
  experience VARCHAR(10) NOT NULL,
  position VARCHAR(30) NOT NULL,
  throwing VARCHAR(3) NOT NULL,
  batting VARCHAR(3) NOT NULL,
  introduction VARCHAR(1000) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS mypages (
  id SERIAL NOT NULL,
  user_id INT NOT NULL,
  path VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
 );

CREATE TABLE IF NOT EXISTS teams (
  team_id SERIAL NOT NULL,
  user_id INT NOT NULL,
  name VARCHAR(15) NOT NULL,
  read VARCHAR(15) NOT NULL,
  prefecture VARCHAR(5) NOT NULL,
  city VARCHAR(10) NOT NULL,
  experience VARCHAR(50) NOT NULL,
  formation VARCHAR(12) NOT NULL,
  frequency VARCHAR(30) NOT NULL,
  activity_days VARCHAR(30) NOT NULL,
  match_days VARCHAR(30) NOT NULL,
  team_introduction VARCHAR(1000) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL, 
  PRIMARY KEY (team_id)
);

CREATE TABLE IF NOT EXISTS teampages (
  id SERIAL NOT NULL,
  team_Id INT NOT NULL,
  path VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS matchboards (
  id SERIAL NOT NULL,
  dateandtime VARCHAR(30) NOT NULL,
  title VARCHAR(30) NOT NULL,
  prefecture VARCHAR(5) NOT NULL,
  ground VARCHAR(30) NOT NULL,
  referee VARCHAR(3) NOT NULL,
  cost VARCHAR(30) NOT NULL,
  helpmember VARCHAR(10) NOT NULL, 
  comments VARCHAR(50) NOT NULL, 
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL, 
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS memberboards (
  id SERIAL NOT NULL,
  title VARCHAR(30) NOT NULL,
  newbieposition VARCHAR(20) NOT NULL,
  prefecture VARCHAR(5) NOT NULL,
  city VARCHAR(10) NOT NULL,
  age_min VARCHAR(3) NOT NULL,
  age_max VARCHAR(3) NOT NULL,
  frequency VARCHAR(10) NOT NULL,
  activity_days VARCHAR(10) NOT NULL,
  match_days VARCHAR(10) NOT NULL,
  newplayer VARCHAR(10) NOT NULL, 
  team_pr VARCHAR(1000) NOT NULL, 
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL, 
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS matchforms(
  id SERIAL NOT NULL,
  user_id INT NOT NULL,
  team_id INT NOT NULL,
  message VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
